apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: python1-to-python2-routing
  namespace: python1
spec:
  hosts:
    - "python1.apps.source-lab.io"
    - "python1.python1.svc.cluster.local"
  http:
    - match:
        - uri:
            prefix: "/greeting"
      route:
        - destination:
            host: python2.python2.svc.cluster.local
            port:
              number: 8080
          subset: v1
          weight: 90
        - destination:
            host: python2.python2.svc.cluster.local
            port:
              number: 8080
          subset: v2
          weight: 10
