apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: {{ cookiecutter.component.name }}-rate-limit
  namespace: {{ cookiecutter.component.attributes.namespace }}
plugin: rate-limiting
config:
  second: 100
  policy: local # Use "local" for a single Kong instance, "redis" for distributed rate limiting
