pilot:
  autoscaleEnabled: true
  autoscaleMin: 1
  autoscaleMax: 5
  replicaCount: 1
  resources:
    requests:
      cpu: 500m
      memory: 2048Mi

global:
  proxy:
    image: docker.io/istio/proxyv2:1.10.0
    autoInject: enabled
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1024Mi

meshConfig:
  enablePrometheusMerge: true

sidecarInjectorWebhook:
  rewriteAppHTTPProbe: true

telemetry:
  enabled: true
  v2:
    enabled: true
    prometheus:
      enabled: true

revision: ""
