replicaCount: 1

kind: Deployment

serviceAccount:
  create: true

podAnnotations:
  prometheus.io/port: "15020"
  prometheus.io/scrape: "true"
  prometheus.io/path: "/stats/prometheus"
  inject.istio.io/templates: "gateway"
  sidecar.istio.io/inject: "true"

service:
  type: LoadBalancer
  ports:
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443

resources:
  requests:
    cpu: 100m
    memory: 128Mi

imagePullPolicy: IfNotPresent
