global:
  hub: docker.io/istio
  tag: latest
  proxy:
    image: proxyv2

pilot:
  image: pilot
  resources:
    requests:
      cpu: 500m
      memory: 2048Mi

meshConfig:
  enablePrometheusMerge: true

sidecarInjectorWebhook:
  rewriteAppHTTPProbe: true

telemetry:
  enabled: true
  v2:
    enabled: true
    prometheus:
      enabled: true


