global:
  hub: docker.io/istio
  tag: 1.10.0
  proxy:
    image: proxyv2

pilot:
  image: pilot
  resources:
    requests:
      cpu: 500m
      memory: 2048Mi

meshConfig:
  enablePrometheusMerge: true

sidecarInjectorWebhook:
  rewriteAppHTTPProbe: true

telemetry:
  enabled: true
  v2:
    enabled: true
    prometheus:
      enabled: true

  base:
    # For istioctl usage to disable istio config crds in base
    enableIstioConfigCRDs: true
