pilot:
  autoscaleEnabled: true
  autoscaleMin: 1
  autoscaleMax: 5
  replicaCount: 1
  resources:
    requests:
      cpu: 500m
      memory: 2048Mi

global:
  defaultPodDisruptionBudget:
    enabled: true
  defaultResources:
    requests:
      cpu: 10m
  hub: gcr.io/istio-testing
  tag: latest
  istiod:
    enableAnalysis: false
  proxy:
    autoInject: enabled
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1024Mi
  proxy_init:
    image: proxyv2

meshConfig:
  enablePrometheusMerge: true

sidecarInjectorWebhook:
  rewriteAppHTTPProbe: true

telemetry:
  enabled: true
  v2:
    enabled: true
    prometheus:
      enabled: true

revision: ""
