resources:
  - namespace.yaml
  - istio-control.yaml
  - istio-base.yaml
  {%- if cookiecutter.component.attributes.kiali %}
  - istio-kiali.yaml
  {%- endif %}
  {%- if cookiecutter.__ingress %}
  - service_entry.yaml
  {%- endif %}
