
{%- if cookiecutter.links_from and any(link['mtls'] is defined and link['mtls'] for link in cookiecutter.links_from.values()) %}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: example-namespace
spec:
  mtls:
    mode: STRICT
{%- endif %}