{% for link in cookiecutter.links_to.values() %}
  {%- if link.component.attributes.mtls %}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name:  {{ link.component.name }}
  namespace: {{ link.component.attributes.namespace }}
spec:
  mtls:
    mode: STRICT
---
{% endif %}
  {% endfor %}
