apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: kong-service-entry
spec:
  hosts:
    - "*.{{ cookiecutter.configuration.domain }}"
    - "kong.kong.svc.cluster.local"
  location: MESH_EXTERNAL
  ports:
    - number: 80
      name: http
      protocol: HTTP
    - number: 443
      name: https
      protocol: HTTPS