configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero
      config:
        s3ForcePathStyle: "true"
        s3Url: https://api.{{ cookiecutter.component.name }}.{{ cookiecutter.configuration.domain }}
        insecureSkipTLSVerify: "true"


initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.2.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

credentials:
  useSecret: true
  secretContents:
    cloud: |
      [default]
      {%- for service in cookiecutter.components.values() if service.type == 'minio' %}
      aws_access_key_id={{ service.attributes.access_key }}
      aws_secret_access_key={{ service.attributes.secret_key }}
      {%- endfor %}

