configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: {{ cookiecutter.links_to.minio.attributes.bucket }}
      config:
        s3ForcePathStyle: "true"
        region: minio
        s3Url: http://minio.minio.svc.cluster.local:9000
        publicUrl: https://api.{{ cookiecutter.component.name }}.{{ cookiecutter.configuration.domain }}
        insecureSkipTLSVerify: "true"
  volumeSnapshotLocation: []

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.2.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

credentials:
  useSecret: true
  secretContents:
    cloud: |
      [default]
      aws_access_key_id={{ cookiecutter.links_to.minio.attributes.access_key }}
      aws_secret_access_key={{ cookiecutter.links_to.minio.attributes.secret_key }}


