configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero
      config:
        region: minio
        s3ForcePathStyle: "true"
        s3Url: https://api.{{ cookiecutter.component.name }}.{{ cookiecutter.configuration.domain }}
  volumeSnapshotLocation:
    - name: default
      provider: aws
      config:
        region: minio
credentials:
  useSecret: true
  existingSecret: minio-credentials
