configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero
      config:
        region: minio
        s3ForcePathStyle: "true"
        s3Url: https://api.{{ cookiecutter.component.name }}.{{ cookiecutter.configuration.domain }}
  volumeSnapshotLocation:
    - name: default
      provider: aws
      config:
        region: minio
credentials:
  useSecret: true
  existingSecret: minio-credentials

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.2.0 # Use the latest version compatible with your Velero installation
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

credentials:
  useSecret: true
  secretContents:
    cloud: |
      [default]
      {%- for service in cookiecutter.components.values() if service.type == 'minio' %}
      aws_access_key_id={{ service.attributes.access_key }}
      aws_secret_access_key={{ service.attributes.secret_key }}
      {%- endfor %}

