apiVersion: batch/v1
kind: Job
metadata:
  name: minio-bucket-setup
  namespace: minio
spec:
  template:
    spec:
      containers:
        - name: minio-setup
          image: minio/mc:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              mc alias --insecure set myminio https://api.{{ cookiecutter.component.name }}.{{ cookiecutter.configuration.domain }} $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
              # Wait for MinIO endpoint to become available
              until mc --insecure admin info myminio; do
                echo 'Waiting for MinIO to become available...'
                sleep 10
              done
              # Check if the bucket exists
              if ! mc ls --insecure myminio/velero; then
                # Attempt to create the bucket
                if mc mb --insecure myminio/velero; then
                  echo "Bucket 'velero' created successfully."
                  # mc policy set public --insecure myminio/velero
                else
                  echo "Failed to create bucket 'velero'."
                  exit 1
                fi
              else
                echo "Bucket 'velero' already exists."
              fi
              
 

          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: aws_secret_access_key
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: aws_access_key_id
      restartPolicy: Never
  backoffLimit: 4

