resources:
  - namespace.yaml
  - crds/
  - bucket-create.yaml
  - velero.yaml

labels:
  - pairs:
      stacktic.io/app: "{{ cookiecutter.component.name }}"
      stacktic.io/group: "{{cookiecutter.component.group }}"
      stacktic.io/namespace: "{{ cookiecutter.component.attributes.namespace }}"
    includeTemplates: true

secretGenerator:
  - name: minio-credentials
    namespace: {{ cookiecutter.component.attributes.namespace }}
    envs:
      - secret/minio.env