{% for service in cookiecutter.components.values() if service.group == 'rel_db' or service.group == 'doc_db' or service.group == 'broker' %}
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: {{ service.name }}-backup
  namespace: {{ cookiecutter.component.attributes.namespace }}
spec:
  includedNamespaces:
    - {{ service.attributes.namespace }}
  includedResources:
    - persistentvolumeclaims
    - persistentvolumes
  labelSelector:
    matchLabels:
      stacktic.io/app: "{{ service.name }}"
  storageLocation: default
  ttl: 24h0m0s
---
{% endfor %}
